import fs from 'node:fs/promises';
import {load} from 'cheerio';
import crypto from 'node:crypto';
import {assertBuyingPolicy} from '../src/lib/buying-policy.mjs';
import {applyImageOverrides} from '../src/lib/image-overrides.mjs';
import {applyAddressCorrections,assertAddressIntegrity,businessProfile} from '../src/lib/address-integrity.mjs';
import {capturedProfiles} from '../src/lib/social-profiles.mjs';
const pages=applyImageOverrides(applyAddressCorrections(JSON.parse(await fs.readFile('src/data/pages.json','utf8'))));
assertAddressIntegrity(pages);assertBuyingPolicy(pages);
const assets=JSON.parse(await fs.readFile('migration/assets.json','utf8'));
const imageByPath=new Map(assets.map(a=>[a.path,a.url]));
try{const optimized=JSON.parse(await fs.readFile('migration/image-optimization.json','utf8'));for(const [original,item]of Object.entries(optimized.images))imageByPath.set(item.path,imageByPath.get(original));}catch{}
const id=s=>'page-'+crypto.createHash('sha256').update(s).digest('hex').slice(0,24);
let serial=0;const key=()=>String(++serial);
function portable(html,article=false){const $=load(html);if(article)$('.article-takeaway,.article-toc,.article-resources,.article-related,.article-next-step').remove();const body=[];
 function inline(nodes,marks=[],defs=[]){const spans=[];for(const n of nodes){if(n.type==='text'){if(n.data)spans.push({_type:'span',_key:key(),text:n.data,marks});continue}if(n.type!=='tag')continue;let next=marks;if(['strong','b','em','i','u','code','s'].includes(n.name))next=[...marks,({b:'strong',i:'em'}[n.name]||n.name)];if(n.name==='a'&&$(n).attr('href')){const k=key();defs.push({_type:'link',_key:k,href:$(n).attr('href')});next=[...marks,k]}if(n.name==='br')spans.push({_type:'span',_key:key(),text:'\n',marks});else spans.push(...inline(n.children||[],next,defs));}return spans}
 function walk(nodes,level=0){for(const n of nodes){if(n.type==='text'){const text=n.data.trim();if(text)body.push({_type:'block',_key:key(),style:'normal',markDefs:[],children:[{_type:'span',_key:key(),text,marks:[]}]});continue}if(n.type!=='tag')continue;const el=$(n);if(el.hasClass('integration-notice')||el.hasClass('background-photo')||el.hasClass('article-toc'))continue;
 if(n.name==='img'){const src=el.attr('src');body.push({_type:'migratedImage',_key:key(),sourceUrl:imageByPath.get(src)||(/^https?:/.test(src)?src:undefined),localPath:src,alt:el.attr('alt')||'',caption:el.closest('figure').children('figcaption').text()||undefined,width:Number(el.attr('width'))||undefined,height:Number(el.attr('height'))||undefined,srcset:el.attr('srcset'),sizes:el.attr('sizes')});continue}
 if(n.name==='figcaption')continue;
 if(n.name==='table'){body.push({_type:'sourceTable',_key:key(),rows:el.find('tr').map((i,tr)=>({_type:'tableRow',_key:key(),isHeader:$(tr).children('th').length>0&&$(tr).children('td').length===0,cells:$(tr).children('td,th').map((j,td)=>$(td).text()).get()})).get()});continue}
 if(['ul','ol'].includes(n.name)){for(const li of el.children('li').toArray()){const defs=[];body.push({_type:'block',_key:key(),style:'normal',listItem:n.name==='ol'?'number':'bullet',level:level+1,markDefs:defs,children:inline($(li).contents().filter((i,e)=>!['ul','ol'].includes(e.name)).toArray(),[],defs)});walk($(li).children('ul,ol').toArray(),level+1)}continue}
 if(/^(p|h[1-6]|blockquote|summary)$/.test(n.name)){const defs=[];body.push({_type:'block',_key:key(),style:n.name==='h1'?'h2':/^h/.test(n.name)?n.name:n.name==='blockquote'?'blockquote':'normal',sourceId:el.attr('id'),className:el.attr('class'),markDefs:defs,children:inline(n.children||[],[],defs)});for(const img of el.find('img').toArray())walk([img]);continue}
 walk(n.children||[],level);
 }}walk($('body').contents().toArray());return body.filter(b=>b._type!=='block'||b.children?.some(c=>c.text.trim()));}
const reference=_ref=>({_type:'reference',_ref});
const authorId=name=>'author-'+crypto.createHash('sha256').update(name).digest('hex').slice(0,16);
const serviceId=path=>'service-'+id(path).slice(5);
const categoryId=title=>'source-category-'+crypto.createHash('sha256').update(title).digest('hex').slice(0,16);
for(const p of pages.filter(p=>p.isArticle))if(!p.editorial?.focusKeyword||!p.editorial?.sources?.length||!p.editorial?.images?.length)throw new Error('Article must be optimized before CMS export: '+p.path);
const documents=pages.map(p=>({_id:id(p.path),_type:'page',title:p.heading,path:p.path,kind:p.isArticle?'article':p.path==='/sell-your-golds/'?'service':p.path.startsWith('/tag/')?'archive':'page',contentMode:'imported',body:portable(p.html,p.isArticle),legacyAnchors:load(p.html)('[id]').map((i,e)=>e.attribs.id).get(),seo:{_type:'seo',title:p.title,description:p.description,canonical:p.canonical||'https://cash4goldanddiamond.com'+p.path,noindex:p.robots.includes('noindex'),nofollow:p.robots.includes('nofollow'),focusKeyword:p.editorial?.focusKeyword,secondaryKeywords:p.editorial?.secondaryKeywords,sourceSocialImage:p.meta?.find(m=>m.name==='og:image')?.content},publishedAt:p.publishedAt,author:p.isArticle?reference(authorId(p.author)):undefined,location:reference('location-downtown'),service:p.editorial?.service?reference(serviceId(p.editorial.service)):undefined,categories:[...(p.categories||[]).map((title,i)=>({_key:'source-'+i,...reference(categoryId(title))})),...(p.editorial?.group?[{_key:p.editorial.group,...reference('category-'+p.editorial.group)}]:[])],answer:p.editorial?.answer,sources:p.editorial?.sources?.map((s,i)=>({_key:'source-'+i,_type:'citation',...s})),related:p.editorial?.related?.map((path,i)=>({_key:'related-'+i,...reference(id(path))})),sourceUrl:p.sourceUrl,sourceSha256:p.sourceSha256,contentVerified:false,seoVerified:false}));
documents.push({_id:'business-main',_type:'business',name:businessProfile.name,phone:businessProfile.phone,email:businessProfile.email,address:businessProfile.address,locations:[{_key:'downtown',...reference('location-downtown')}]},{_id:'location-downtown',_type:'location',name:'Downtown Los Angeles Jewelry District',streetAddress:businessProfile.streetAddress,city:businessProfile.city,region:businessProfile.region,postalCode:businessProfile.postalCode,phone:businessProfile.phone,mapsUrl:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(businessProfile.address)});
for(const name of new Set(pages.filter(p=>p.isArticle).map(p=>p.author)))documents.push({_id:authorId(name),_type:'author',name});
const servicePaths=[...new Set(pages.map(p=>p.editorial?.service).filter(Boolean))];
for(const path of servicePaths){const p=pages.find(p=>p.path===path);documents.push({_id:serviceId(path),_type:'service',title:p.heading,page:reference(id(path)),summary:p.description,locations:[{_key:'downtown',...reference('location-downtown')}]});}
for(const [key,title]of Object.entries({gold:'Gold, scrap and coins',diamond:'Diamonds',watch:'Rolex and luxury watches',gemstone:'Large, high-quality gemstones',estate:'Estate and fine jewelry'}))documents.push({_id:'category-'+key,_type:'category',title});
for(const title of new Set(pages.flatMap(p=>p.categories||[])))documents.push({_id:categoryId(title),_type:'category',title});
const redirectMap=JSON.parse(await fs.readFile('src/data/redirects.json','utf8'));
for(const [from,to] of Object.entries(redirectMap))documents.push({_id:'redirect-'+id(from).slice(5),_type:'redirect',from,to,status:301});
for(const p of pages){const $=load(p.html),faqs=[];$('details').each((i,e)=>{const question=$(e).children('summary').text().trim(),answer=$(e).children('div').text().trim();if(question&&answer)faqs.push({question,answer});});if(p.isArticle)$('h2,h3,h4').each((i,e)=>{const question=$(e).text().trim(),answer=$(e).next('p').text().trim();if(question.endsWith('?')&&answer&&!faqs.some(f=>f.question===question))faqs.push({question,answer});});const doc=documents.find(d=>d._id===id(p.path));doc.faqs=faqs.slice(0,12).map((f,i)=>{const _id=id(p.path+'#faq'+i);documents.push({_id,_type:'faq',...f,page:reference(id(p.path))});return {_key:'faq-'+i,...reference(_id)};});}
documents.push({_id:'navigation-main',_type:'navigation',title:'Main navigation',items:[['Home','/'],['About','/about-us-sell-gold-and-diamonds-online/'],['Start Selling','/start-selling-gold-and-diamonds/'],['Blogs','/blogs/'],['Reviews','/reviews/'],['FAQ','/faqs/'],['Contact Us','/contact-us/']].map(([label,href])=>({_key:key(),_type:'navigationLink',label,href}))});
documents.find(document=>document._id==='business-main').socialProfiles=capturedProfiles.map(profile=>profile.href);
const socialBacklog=JSON.parse(await fs.readFile('migration/pre-deployment/social-backlog.json','utf8').catch(error=>{if(error.code==='ENOENT')return '{"rows":[]}';throw error;}));
for(const row of socialBacklog.rows){const doc=documents.find(d=>d.path===row.path);if(doc)doc.socialSharing={_type:'socialSharing',enabled:false,channels:['facebook','instagram'],facebookCaption:row.facebookCaption,instagramCaption:row.instagramCaption,localImage:row.image,imageAlt:row.imageAlt,approved:false,mediaRightsConfirmed:false};}
documents.push({_id:'social-automation',_type:'socialAutomation',enabled:false,channels:['facebook','instagram'],schedule:'Monday, Wednesday and Friday at 10:00 a.m. America/Los_Angeles'});
await fs.writeFile('migration/sanity-import.ndjson',documents.map(d=>JSON.stringify(d)).join('\n')+'\n');console.log('Prepared',documents.length,'structured Sanity documents. No remote import performed.');
